// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS7uDoHu8HvvixH8KptS5davONiXgsdaQ',
    appId: '1:840513677952:web:480586e2537c5fd3219465',
    messagingSenderId: '840513677952',
    projectId: 'tido-678e7',
    authDomain: 'tido-678e7.firebaseapp.com',
    storageBucket: 'tido-678e7.appspot.com',
    measurementId: 'G-CC3REGC975',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPWLCG8zBzTw_h918PCBRdFAk6VXKc1f0',
    appId: '1:840513677952:android:4907d5828c04e86c219465',
    messagingSenderId: '840513677952',
    projectId: 'tido-678e7',
    storageBucket: 'tido-678e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwB86PjssHPPjQH_0er5ZXoQ6c63CHcKk',
    appId: '1:840513677952:ios:eccebb237d03ff9f219465',
    messagingSenderId: '840513677952',
    projectId: 'tido-678e7',
    storageBucket: 'tido-678e7.appspot.com',
    iosBundleId: 'com.example.tido',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwB86PjssHPPjQH_0er5ZXoQ6c63CHcKk',
    appId: '1:840513677952:ios:eccebb237d03ff9f219465',
    messagingSenderId: '840513677952',
    projectId: 'tido-678e7',
    storageBucket: 'tido-678e7.appspot.com',
    iosBundleId: 'com.example.tido',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS7uDoHu8HvvixH8KptS5davONiXgsdaQ',
    appId: '1:840513677952:web:1162e86d8838244d219465',
    messagingSenderId: '840513677952',
    projectId: 'tido-678e7',
    authDomain: 'tido-678e7.firebaseapp.com',
    storageBucket: 'tido-678e7.appspot.com',
    measurementId: 'G-C40J5JE8F6',
  );
}
